name: Bump Image Version
description: Bump Docker Image To Version Specified In Input

inputs:
  package_version_api_url:
    description: "URL to access package version"
    required: true
  bump:
    description: "Version to bump to, patch, minor, and major"
    default: patch
    required: true
  github_token:
    description: "Github Token"
    required: true

outputs:
  updated_version:
    description: "Updated version that image will be bumped to"
    value: ${{ steps.bumped_version.outputs.NEW_VERSION }}

runs:
  using: "composite"
  steps:
    - uses: build-trust/.github/actions/get_latest_image_version@custom-actions
      id: current_latest_version
      with:
        package_version_api_url: ${{ inputs.package_version_api_url }}
        github_token: ${{ inputs.github_token }}

    - shell: bash
      id: bumped_version
      run: |
        current_version="${{ steps.current_latest_version.outputs.latest_version }}"
        bump="${{ inputs.bump }}"

        if [[ -n $bump ]]; then
          echo "Bumping version $current_version as ${bump} specified in workflow dispatch"
          bumped_version=$(semver bump ${bump} ${current_version})
        else
          echo "Setting BUMP version to patch as job is a cron-job"
          bumped_version=$(semver bump patch ${current_version})
        fi

        echo "NEW_VERSION=$bumped_version" >> $GITHUB_OUTPUT
