name: Check If Ockam Elixir Dep Need An Update
description: Check If Ockam Elixir Dependency Need An Update

inputs:
  repository_name:
    description: "Repository Name"
    required: true
  csv_file_path:
    description: "CSV File Path"
    required: true
  log_branch:
    description: "Branch Where CSV Log Is Stored"
    required: true

outputs:
  run_is_unique:
    description: "Indicates If There Was Indeed An Update"
    value: ${{ steps.unique_runner.outputs.commit_already_built }}
  ockam_ref:
    description: "Ockam Commit"
    value: ${{ steps.ockam_ref.outputs.ref }}

runs:
  using: composite
  steps:
    - uses: actions/checkout@bf085276cecdb0cc76fbbe0687a5a0e786646936
      with:
        repository: 'build-trust/ockam'
        path: 'ockam'
        fetch-depth: 0

    - uses: actions/checkout@bf085276cecdb0cc76fbbe0687a5a0e786646936
      with:
        path: ${{ inputs.repository_name }}
        ref: ${{ inputs.log_branch }}
        fetch-depth: 0

    - shell: bash
      id: ockam_ref
      working-directory: ockam
      run: |
        sha=$(git rev-parse HEAD)
        echo "ref=$sha" >> $GITHUB_OUTPUT

    - uses: build-trust/.github/actions/unique_checker@custom-actions
      id: unique_runner
      with:
        path: implementations/rust/elixir
        sha_column: 3
        csv_filepath: ${{ inputs.csv_file_path }}

    - shell: bash
      working-directory: ${{ inputs.repository_name }}
      if: ${{ steps.unique_runner.outputs.commit_already_built == 1 || github.event_name == 'workflow_dispatch' }}
      run: |
        # Update The Repository CSV File
        if [[ ${{ github.event_name }} == 'workflow_dispatch' ]]; then
          actor="${{ github.actor }}"
        else
          actor="cron_log"
        fi

        echo "$actor,$(date +'%b %d %Y %T'),${{ steps.ockam_ref.outputs.ref }}" >> ${{ inputs.csv_file_path }}
        git add ${{ inputs.csv_file_path }}
        git commit -m "log: update dependency for ockam ref ${{ steps.ockam_ref.outputs.ref }}"

        git pull --rebase
        git push


    - if: ${{ steps.unique_runner.outputs.commit_already_built == 0 && github.event_name != 'workflow_dispatch' }}
      uses: build-trust/.github/actions/cancel_workflow@custom-actions
